#!/bin/sh

# Detect architecture and set proper URL
ARCH=$(uname -m)
BASE_URL="https://github.com/neovim/neovim/releases/download/stable"

case "$ARCH" in
    x86_64)  FILE="nvim-linux-x86_64.tar.gz" ;;
    aarch64) FILE="nvim-linux-arm64.tar.gz" ;;
    *)
        echo "Unsupported architecture: $ARCH"
        exit 1
        ;;
esac

URL="$BASE_URL/$FILE"

# Download, extract, clean up
curl -L "$URL" -o neovim_tmp.tar.gz
tar -xf neovim_tmp.tar.gz
rm -f neovim_tmp.tar.gz
